### ISSUE TITLE
Pose GT for RGB images

### ISSUE THREAD

**Issue by rahulaggarwal965** [daniilidis-group/m3ed#12]
If I wanted the associated ground truth poses for the "/ovc/rgb/data" rgb images, which indices should I use to index into the "Cn_T_C0" (I assume these are the camera transforms).

Right now, I have an RGB image array that is 2550xHxWx3 and a pose array (Cn_T_C0) of 1020x4x4. Given a timestamp t associated with RGB image A, do I have to find the two closest timestamps in the pose_gt.h5 "ts" dataset and interpolate between the corresponding poses to find the correct pose?

**Comment by fcladera** [comment]
Not urgent, will just leave this here so I don't forget:
 - https://github.com/daniilidis-group/m3ed/issues/12

GT poses are obtained in LiDAR frame, whose frequency is slower  than the camera frames. As data is synchronized, you can interpolate between the two frames to find a pose for the given frame.

Feel free to collaborate your interpolation method to the repo! Otherwise, we hope to have a ground truth interpolation for cameras added into the dataset soon.
