### ISSUE TITLE
Inquiry for the timestamps in hdf5 file and rosbag file

### ISSUE THREAD

**Issue by Sangbum99** [daniilidis-group/m3ed#14]
Hi, I'm the one who wants to use your dataset for my research.

I'm doing Visual SLAM and I've noticed that timestamps of the ground truth (hdf5 file, spot_indoor_building_loop_pose_gt.h5) and rosbag file (spot_indoor_building_loop_pose.bag) are significantly different. 

I realized that your ground truth is from the RTK-GPS, but I have no idea how these timestamps is come from.

It is not Unix time, so let me know what is the reference for the timestamps of ground truth.
For the evaluation of the SLAM algorithm, I need the align the timestamps between ground truth and rosbag file.
Can you let me know how to align hdf5's timestamp to rosbag's timestamp?

This picture below is the extracted timestamp ('\ts' of the spot_indoor_building_loop_pose_gt.h5).
![image](https://github.com/user-attachments/assets/4463de94-33c1-4b3e-ac58-ad7162dc7003)

Thank you for your dataset and helping me.

**Comment by fcladera** [comment]
Copying this answer:

Thank you for your interest in M3ED. Our original intent was to provide HDF5 files that are consistent in time for a given experiment. We corrected any software related time errors that you would see in a ROS bag file through the parameters of the known hardware setup (due to multiple clock sources). This allows us to achieve sub millisecond time synchronization in the sensor readings. If you are interested, we can work with you to provide the offset and skew for each clock to map into an approximate ROS time.

For right now though, I encourage you to utilize only HDF5 files when making these quantitative evaluations as that will lead to the most accurate results.
